// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int? OrderId { get; set; }

    public int? ProductId { get; set; }

    public int? ComboId { get; set; }

    public int? Topping1Id { get; set; }

    public int? Topping2Id { get; set; }

    public int Quantity { get; set; }

    public decimal SubTotal { get; set; }

    public virtual Combo Combo { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual Topping Topping1 { get; set; }

    public virtual Topping Topping2 { get; set; }
}