// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class Topping
{
    public int ToppingId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string ImageUrl { get; set; }

    public int Stock { get; set; }

    public virtual ICollection<Cart> CartTopping1s { get; set; } = new List<Cart>();

    public virtual ICollection<Cart> CartTopping2s { get; set; } = new List<Cart>();

    public virtual ICollection<OrderDetail> OrderDetailTopping1s { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderDetail> OrderDetailTopping2s { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Combo> Combos { get; set; } = new List<Combo>();
}